#!/usr/bin/env bash
# This script installs nginx on the server and sets up a simple web page

sudo apt-get update
sudo apt-get install -y nginx

sudo chown -R ubuntu /var/www


echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart

sudo update-rc.d nginx defaults
