#!/usr/bin/env bash
# Install Nginx if not already installed
sudo apt update
sudo apt install -y nginx

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

sudo systemctl restart nginx
