#!/usr/bin/env bash
# script that configures nginx to serve a custom 404 page

sudo apt update
sudo apt install -y nginx

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo tee /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF

sudo service nginx restart
