#!/usr/bin/env bash
# bash script that configures nginx to listen on port 80
apt-get update
apt-get install -y nginx
systemctl enable nginx
systemctl start nginx
sudo sed -i '/listen 80 default_server;/s/^#//g' /etc/nginx/sites-available/default
sudo sed -i '/listen \[::\]:80 default_server;/s/^#//g' /etc/nginx/sites-available/default
sudo service nginx restart
netstat -tulnp | grep :80
