#!/usr/bin/env bash
# bash script that configures nginx to listen on port 80
apt-get update
apt-get install -y nginx
systemctl enable nginx
systemctl start nginx
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
netstat -tulnp | grep :80
