#!/usr/bin/env bash
# this script configures a server to only run
# nginx server as nginx user. listen on 8080

sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo nginx -g 'daemon off;'
