#!/usr/bin/env bash
# using the codes in 1-run_nginx file, make your fix short and sweet.
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
